name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/run-build.yml
  call-publish:
    uses: ./.github/workflows/publish-pages.yml