name: Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  call-build:
    uses: ./.github/workflows/run-build.yml
  call-publish:
    needs: call-build
    uses: ./.github/workflows/publish-pages.yml